version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/petclinic.war /main/webapp/petclinic.war
artifacts:
  files:
    - petclinic.war
  discard-paths: yes
